In [1]:
import numpy as np

### Write a function so that the columns of the output matrix are powers of the input vector.

In [9]:
def matrix(vector,n, increasing=False):
    if not increasing:
        matx= np.array([x**(n-1-i) for x in vector for i in range(3)]).reshape(vector.size,n)
    elif increasing:
        matx=np.array([x**i for x in vector for i in range(3)]).reshape(vector.size,n)
        
    return matx

In [10]:
inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = matrix(inputvector,no_col_opmat,False)
op_matx_inc_order =matrix(inputvector,no_col_opmat,True)


In [11]:
op_matx_dec_order

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [29]:
op_matx_inc_order

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

In [12]:
def movingAverage(a, n=3):
    sum=np.cumsum(a,dtype=float)
    sum[n:]= sum[n:]- sum[:-n]
    return sum[n-1:]/n

In [13]:
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [14]:
a1=np.asarray(a)

In [16]:
np.array(movingAverage(a1,n=3)).round(3)

array([  5.   ,   4.667,   5.667,   6.667,   9.667,  28.667,  49.333,
        72.667,  84.   ,  93.333, 116.333])